version: '2'
services:
  statsd:
    container_name: statsd
    image: hopsoft/graphite-statsd
    ports:
      - "81:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_HOST: "grafana.expresso.store"
      VIRTUAL_PORT: "3000"