version: '2'
services:
  bloodlines:
    image: ghmeier/bloodlines
    ports:
      - "8080:8080"
    links:
      - mysql
      - rabbitmq
  mysql:
    image: ghmeier/expresso-mysql
    ports:
      - "3306:3306"
    environment:
      STARTUP_SQL: "/scripts/create_tables.sql"
      MYSQL_PASS: "bloodlines"
  rabbitmq:
    image: ghmeier/rabbitmq-delayed
    ports:
      - "5672:5672"
