version: '2'
services:
  bloodlines:
    container_name: bloodlines
    image: ghmeier/bloodlines
    ports:
      - "8080:8080"
    # links:
    #   - mysql
    #   - rabbitmq
    #   - statsd
    environment:
      VIRTUAL_HOST: "bloodlines.expresso.store"
      VIRTUAL_PORT: "8080"
  coinage:
    container_name: coinage
    image: ghmeier/coinage
    ports:
      - "8081:8081"
    # links:
    #   - mysql
    environment:
      VIRTUAL_HOST: "coinage.expresso.store"
      VIRTUAL_PORT: "8081"
  expresso:
    container_name: expresso
    image: ghmeier/expresso
    ports:
      - "9000:9000"
    environment:
      VIRTUAL_HOST: "expresso.store"
      VIRTUAL_PORT: "9000"
