CREATE DATABASE bloodlines;
USE bloodlines;
DROP TABLE IF EXISTS content;
CREATE TABLE content(
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	contentType VARCHAR(20) NOT NULL,
	text varchar(4096) NOT NULL,
	parameters VARCHAR(1024),
	status VARCHAR(20) NOT NULL,
	subject varchar(1024)
);
DROP TABLE IF EXISTS job;
CREATE TABLE job(
	sendTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	sendStatus VARCHAR(20) NOT NULL,
	receipts VARCHAR(4096) NOT NULL
);
DROP TABLE IF EXISTS preference;
CREATE TABLE preference(
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	email VARCHAR(20) NOT NULL,
	userId VARCHAR(36) NOT NULL
);
DROP TABLE IF EXISTS receipt;
CREATE TABLE receipt(
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	sendState VARCHAR(20) NOT NULL,
	vals VARCHAR(4096) NOT NULL,
	contentId VARCHAR(36) NOT NULL, FOREIGN KEY fk_content(contentId) REFERENCES content(id),
	userId VARCHAR(36) NOT NULL
);
DROP TABLE IF EXISTS b_trigger;
CREATE TABLE b_trigger(
	id VARCHAR(36) NOT NULL,
	tkey VARCHAR(1024) NOT NULL,
	vals VARCHAR(4096) NOT NULL,
	contentId  VARCHAR(36) NOT NULL, FOREIGN KEY fk_triggercontent(contentId) REFERENCES content(id),
	PRIMARY KEY (id)
);
